Repository MOONSHOT-Team/MOONSHOT-SERVER, pull requests merged in 2023-12, with the labels that each got.

#2 [Feat] #1 - 프로젝트 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/moonshot/server/ServerApplication.java
  src/main/java/org/moonshot/server/domain/user/controller/controller
  src/main/java/org/moonshot/server/domain/user/dto/dto
  src/main/java/org/moonshot/server/domain/user/exception/exception
  src/main/java/org/moonshot/server/domain/user/model/model
  src/main/java/org/moonshot/server/domain/user/repository/repo
  src/main/java/org/moonshot/server/domain/user/service/service
  src/main/java/org/moonshot/server/global/auth/auth
  src/main/java/org/moonshot/server/global/common/common
  src/main/java/org/moonshot/server/global/config/conf
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/org/moonshot/server/ServerApplicationTests.java
Labels: 민철👃🏼

#6 [Feat] Spring Security 설정
  src/main/java/org/moonshot/server/global/auth/auth
  src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java
  src/main/java/org/moonshot/server/global/common/common
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/config/conf
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 민철👃🏼

#9 [Feat] #8 - CommonAPIResponse, CommonException 구현
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/common/exception/MoonshotException.java
  src/main/java/org/moonshot/server/global/common/response/ApiResponse.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 영린🐣

#11 [Feat] #10 - CI/CD 구축
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
  build.gradle
  deploy.sh
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 영린🐣, 민철👃🏼

#13 [Docs] #12 - README.md 업데이트
  README.md
Labels: 영린🐣, 민철👃🏼
