Repository MOONSHOT-Team/MOONSHOT-SERVER, pull requests merged in 2024-02, with the labels that each got.

#201 [Feat] #200 - ObjectiveService 테스트 코드 작성 및 OSIV 설정 변경
  .gitignore
  build.gradle
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/ModifyObjectiveRequestDto.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/OKRCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/response/HistoryResponseDto.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/resources/application-dev.yml
  moonshot-api/src/main/resources/application.yml
  moonshot-api/src/test/java/org/moonshot/objective/service/ObjectiveServiceTest.java
  moonshot-domain/src/main/java/org/moonshot/objective/dto/request/ModifyIndexRequestDto.java
  moonshot-domain/src/main/java/org/moonshot/user/model/User.java
Labels: 민철👃🏼

#203 [Feat] #202 - Task 삭제 API 구현
  moonshot-api/src/main/java/org/moonshot/task/controller/TaskApi.java
  moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
Labels: 영린🐣

#205 [Fix] #204 - Swagger 안보이는 버그 수정
  moonshot-api/build.gradle
  moonshot-api/src/main/java/org/moonshot/config/SwaggerConfig.java
  moonshot-api/src/main/resources/application.yml
  moonshot-common/build.gradle
Labels: 민철👃🏼

#207 [Feat] #206 - DB Migration(Flyway) 적용하기 및 유저 isDeleted 필드 추가
  moonshot-api/build.gradle
  moonshot-api/src/main/resources/application-dev.yml
  moonshot-api/src/main/resources/application.yml
  moonshot-api/src/main/resources/db/migration/V1__add_is_deleted_field.sql
  moonshot-domain/src/main/java/org/moonshot/user/model/User.java
Labels: 민철👃🏼

#209 [Fix] #208 - 카카오 로그인 Origin에 따라 RedirectUri 변경하도록 수정
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/application.yml
  moonshot-common/src/main/java/org/moonshot/filter/MDCFilter.java
  moonshot-common/src/main/java/org/moonshot/util/HttpRequestUtil.java
  moonshot-common/src/main/java/org/moonshot/util/MDCUtil.java
Labels: 민철👃🏼

#210 [Hotfix] #208 - 카카오 로그인 URL 체크 로깅
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
Labels: 민철👃🏼

#211 [Del] #208 - 카카오 로그인 URL 체크 로깅 삭제
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
Labels: 민철👃🏼

#216 [Feat] #215 - Api AOP Logger 추가
  moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultController.java
  moonshot-api/src/main/java/org/moonshot/log/controller/LogController.java
  moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveController.java
  moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java
  moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java
  moonshot-api/src/main/resources/application.yml
Labels: 🚀SP1, 민철👃🏼

#217 [Feat] #214 - 회원탈퇴 SoftDelete 구현
  moonshot-api/src/main/java/org/moonshot/config/SchedulerConfig.java
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserDeleteScheduler.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/db/migration/V2__add_deleteAt_field.sql
  moonshot-domain/src/main/java/org/moonshot/keyresult/repository/KeyResultRepository.java
  moonshot-domain/src/main/java/org/moonshot/log/repository/LogRepository.java
  moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveJpaRepository.java
  moonshot-domain/src/main/java/org/moonshot/task/repository/TaskRepository.java
  moonshot-domain/src/main/java/org/moonshot/user/model/SocialPlatform.java
  moonshot-domain/src/main/java/org/moonshot/user/model/User.java
  moonshot-domain/src/main/java/org/moonshot/user/repository/UserRepository.java
Labels: 🚀SP1, 영린🐣

#219 [Fix] #218 - 개발, 운영서버 분리
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
  Dockerfile-dev
  moonshot-api/src/main/resources/application-dev.yml
Labels: 🚀SP1, 영린🐣, 민철👃🏼

#221 [Fix] #220 - CI, CD job name 변경
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
  Dockerfile
  moonshot-api/src/main/resources/logback-prod.xml
Labels: 🚀SP1, 민철👃🏼

#224 [Fix] #223 - prod-CD.yml 버그 수정
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: 🚀SP1, 민철👃🏼

#225 [Deploy] 운영서버 v1.0.0 배포
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: DEPLOY💻

#226 [Fix] #223 - prod CI, CD.yml 버그 수정
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: 🚀SP1, 민철👃🏼

#227 [Deploy] 운영서버 v1.0.0 배포
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: DEPLOY💻

#229 [Fix] #228 - 클라이언트 에러 대응
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/application.yml
  moonshot-auth/src/main/java/org/moonshot/config/SecurityConfig.java
  moonshot-auth/src/main/java/org/moonshot/filter/MoonshotExceptionHandler.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtValidationType.java
  moonshot-auth/src/main/java/org/moonshot/security/CustomAccessDeniedHandler.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtExceptionFilter.java
  moonshot-auth/src/main/java/org/moonshot/security/UserAuthentication.java
Labels: 🚀SP1, 민철👃🏼

#230 [Deploy] 운영서버 v1.0.1 배포
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/application.yml
  moonshot-auth/src/main/java/org/moonshot/config/SecurityConfig.java
  moonshot-auth/src/main/java/org/moonshot/filter/MoonshotExceptionHandler.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtValidationType.java
  moonshot-auth/src/main/java/org/moonshot/security/CustomAccessDeniedHandler.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtExceptionFilter.java
  moonshot-auth/src/main/java/org/moonshot/security/UserAuthentication.java
Labels: DEPLOY💻

#232 [Feat] #231 - User, Log, Task Validator 분리
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/keyresult/service/validator/KeyResultValidator.java
  moonshot-api/src/main/java/org/moonshot/log/service/LogService.java
  moonshot-api/src/main/java/org/moonshot/log/service/validator/LogValidator.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/java/org/moonshot/objective/service/validator/ObjectiveValidator.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/task/service/validator/TaskValidator.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/java/org/moonshot/user/service/validator/UserValidator.java
  moonshot-api/src/main/java/org/moonshot/validator/IndexValidator.java
Labels: 🚀SP1, 영린🐣

#234 [Fix] #233 - Log 이전 로그값이 0으로 뜨는 버그 해결
  moonshot-api/src/main/java/org/moonshot/log/service/LogService.java
Labels: 🚀SP1, 영린🐣

#235 [Deploy] 운영서버 v1.0.1 배포
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/keyresult/service/validator/KeyResultValidator.java
  moonshot-api/src/main/java/org/moonshot/log/service/LogService.java
  moonshot-api/src/main/java/org/moonshot/log/service/validator/LogValidator.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/java/org/moonshot/objective/service/validator/ObjectiveValidator.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/task/service/validator/TaskValidator.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/java/org/moonshot/user/service/validator/UserValidator.java
  moonshot-api/src/main/java/org/moonshot/validator/IndexValidator.java
Labels: DEPLOY💻
