Repository MOONSHOT-Team/MOONSHOT-SERVER, pull requests merged in 2024-03, with the labels that each got.

#237 [Feat] 현재 로그인한 유저 어노테이션 구현
  build.gradle
  moonshot-api/build.gradle
  moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultApi.java
  moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultController.java
  moonshot-api/src/main/java/org/moonshot/log/controller/LogApi.java
  moonshot-api/src/main/java/org/moonshot/log/controller/LogController.java
  moonshot-api/src/main/java/org/moonshot/objective/controller/IndexApi.java
  moonshot-api/src/main/java/org/moonshot/objective/controller/IndexController.java
  moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveApi.java
  moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveController.java
  moonshot-api/src/main/java/org/moonshot/task/controller/TaskApi.java
  moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/user/controller/UserApi.java
  moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-auth/build.gradle
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java
  moonshot-auth/src/main/java/org/moonshot/security/UserAuthentication.java
  moonshot-auth/src/main/java/org/moonshot/security/service/UserPrincipalDetailsService.java
  moonshot-common/src/main/java/org/moonshot/exception/user/UnauthorizedException.java
  moonshot-domain/src/main/java/org/moonshot/user/model/LoginUser.java
  moonshot-domain/src/main/java/org/moonshot/user/model/UserPrincipal.java
  moonshot-domain/src/main/java/org/moonshot/user/repository/UserRepository.java
Labels: 🚀SP1, 민철👃🏼

#239 [Refactor] #238 - Discord 회원가입 로직 이벤트 Pub-Sub 구조로 리팩토링
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-external/src/main/java/org/moonshot/discord/DiscordAppender.java
  moonshot-external/src/main/java/org/moonshot/discord/SignUpEvent.java
  moonshot-external/src/main/java/org/moonshot/discord/SignUpEventListener.java
Labels: 🚀SP1, 민철👃🏼

#242 [Refactor] #240 - 로그인 로직 리팩토링
  moonshot-api/src/main/java/org/moonshot/user/controller/UserApi.java
  moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java
  moonshot-auth/src/main/java/org/moonshot/jwt/JwtValidationType.java
  moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java
  moonshot-common/src/main/java/org/moonshot/constants/JWTConstants.java
  moonshot-common/src/main/java/org/moonshot/exception/global/auth/InvalidRefreshTokenException.java
  moonshot-common/src/main/java/org/moonshot/response/ErrorType.java
Labels: 🚀SP1, 영린🐣

#249 [Fix] KeyResult, Task 생성, 삭제 시 Index 위치 조정 로직 변경
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveJpaRepository.java
Labels: 🚀SP1, 민철👃🏼

#251 [Fix] #250 - Criteria 조건 워딩 변경
  moonshot-domain/src/main/java/org/moonshot/objective/model/Criteria.java
Labels: 🚀SP1, 민철👃🏼

#253 [Refactor] #252 - S3 Presigned Url 서비스 리팩토링
  moonshot-api/src/main/java/org/moonshot/user/controller/ImageController.java
  moonshot-api/src/main/java/org/moonshot/user/dto/response/UserInfoResponse.java
  moonshot-api/src/main/java/org/moonshot/user/service/ImageEventListener.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/application.yml
  moonshot-api/src/main/resources/db/migration/V3__DDL.sql
  moonshot-domain/src/main/java/org/moonshot/keyresult/model/KRState.java
  moonshot-domain/src/main/java/org/moonshot/objective/model/Category.java
  moonshot-domain/src/main/java/org/moonshot/objective/model/Criteria.java
  moonshot-domain/src/main/java/org/moonshot/user/model/User.java
  moonshot-external/build.gradle
  moonshot-external/src/main/java/org/moonshot/s3/ImageEvent.java
  moonshot-external/src/main/java/org/moonshot/s3/ImageType.java
  moonshot-external/src/main/java/org/moonshot/s3/S3Service.java
  moonshot-external/src/main/java/org/moonshot/s3/dto/request/GetPresignedUrlRequestDto.java
  moonshot-external/src/main/java/org/moonshot/s3/dto/request/NotifyImageSaveSuccessRequestDto.java
Labels: 🚀SP1, 민철👃🏼

#254 [Deploy] 운영서버 v1.0.3 배포
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-api/src/main/java/org/moonshot/user/controller/ImageController.java
  moonshot-api/src/main/java/org/moonshot/user/dto/response/UserInfoResponse.java
  moonshot-api/src/main/java/org/moonshot/user/service/ImageEventListener.java
  moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
  moonshot-api/src/main/resources/application.yml
  moonshot-api/src/main/resources/db/migration/V3__DDL.sql
  moonshot-domain/src/main/java/org/moonshot/keyresult/model/KRState.java
  moonshot-domain/src/main/java/org/moonshot/objective/model/Category.java
  moonshot-domain/src/main/java/org/moonshot/objective/model/Criteria.java
  moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveJpaRepository.java
  moonshot-domain/src/main/java/org/moonshot/user/model/User.java
  moonshot-external/build.gradle
  moonshot-external/src/main/java/org/moonshot/s3/ImageEvent.java
  moonshot-external/src/main/java/org/moonshot/s3/ImageType.java
  moonshot-external/src/main/java/org/moonshot/s3/S3Service.java
  moonshot-external/src/main/java/org/moonshot/s3/dto/request/GetPresignedUrlRequestDto.java
  moonshot-external/src/main/java/org/moonshot/s3/dto/request/NotifyImageSaveSuccessRequestDto.java
Labels: DEPLOY💻

#256 [Fix] #255 - KeyResult API, Task API Json 스펙 통일
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultDeleteRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultModifyRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/log/service/LogService.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/KRCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/ObjectiveHistoryRequestDto.java
  moonshot-api/src/main/java/org/moonshot/task/dto/request/TaskSingleCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-common/src/main/java/org/moonshot/constants/WhiteListConstants.java
Labels: 🚀SP1, 영린🐣

#257 [Deploy] v1.0.4 운영서버 배포
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultDeleteRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/dto/request/KeyResultModifyRequestDto.java
  moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java
  moonshot-api/src/main/java/org/moonshot/log/service/LogService.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/KRCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/objective/dto/request/ObjectiveHistoryRequestDto.java
  moonshot-api/src/main/java/org/moonshot/task/dto/request/TaskSingleCreateRequestDto.java
  moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
  moonshot-common/src/main/java/org/moonshot/constants/WhiteListConstants.java
Labels: DEPLOY💻
