Repository MOONSHOT-Team/MOONSHOT-SERVER, pull requests merged in 2024-01, with the labels that each got.

#15 [Feat] Server Exception Discord 연결
  build.gradle
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/common/filter/CachedBodyRequestWrapper.java
  src/main/java/org/moonshot/server/global/common/filter/CachedBodyServletInputStream.java
  src/main/java/org/moonshot/server/global/common/filter/MDCFilter.java
  src/main/java/org/moonshot/server/global/common/filter/ServletWrappingFilter.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/util/ApiCallUtil.java
  src/main/java/org/moonshot/server/global/common/util/HttpRequestUtil.java
  src/main/java/org/moonshot/server/global/common/util/MDCUtil.java
  src/main/java/org/moonshot/server/global/common/util/StringUtil.java
  src/main/java/org/moonshot/server/global/config/FilterConfig.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordWebHook.java
  src/main/java/org/moonshot/server/global/external/discord/exception/ErrorLogAppenderException.java
  src/main/java/org/moonshot/server/global/external/discord/model/Author.java
  src/main/java/org/moonshot/server/global/external/discord/model/EmbedObject.java
  src/main/java/org/moonshot/server/global/external/discord/model/Field.java
  src/main/java/org/moonshot/server/global/external/discord/model/Footer.java
  src/main/java/org/moonshot/server/global/external/discord/model/Image.java
  src/main/java/org/moonshot/server/global/external/discord/model/JsonObject.java
  src/main/java/org/moonshot/server/global/external/discord/model/Thumbnail.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/console-appender.xml
  src/main/resources/discord-appender.xml
  src/main/resources/logback-deploy.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
Labels: 민철👃🏼

#17 [Feat] 이미지 서비스 구현 (w. S3)
  build.gradle
  src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
  src/main/java/org/moonshot/server/domain/user/controller/controller
  src/main/java/org/moonshot/server/global/common/response/ApiResponse.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/AWSConfig.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/constants/AWSConstants.java
  src/main/java/org/moonshot/server/global/external/s3/dto/request/NotifyImageSaveSuccessRequestDto.java
  src/main/java/org/moonshot/server/global/external/s3/dto/response/PresignedUrlVO.java
  src/main/java/org/moonshot/server/global/external/s3/exception/UnsupportedFileExtensionException.java
  src/main/java/org/moonshot/server/global/external/s3/service/S3Service.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 민철👃🏼

#18 [Feat] #14 - 초기 Entity 설계
  src/main/java/org/moonshot/server/domain/Log/model/Log.java
  src/main/java/org/moonshot/server/domain/Log/model/LogState.java
  src/main/java/org/moonshot/server/domain/Task/model/Task.java
  src/main/java/org/moonshot/server/domain/badge/model/Badge.java
  src/main/java/org/moonshot/server/domain/heart/model/Heart.java
  src/main/java/org/moonshot/server/domain/keyResult/model/KRState.java
  src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/objective/model/Category.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/user/model/SocialPlatform.java
  src/main/java/org/moonshot/server/domain/user/model/User.java
  src/main/java/org/moonshot/server/domain/user/model/model
  src/main/java/org/moonshot/server/domain/userBadge/model/UserBadge.java
  src/main/java/org/moonshot/server/global/common/model/Period.java
  src/main/resources/application.yml
Labels: 영린🐣

#21 [Fix] #20 - 패키지명 소문자로 변경
  src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/log/model/Log.java
  src/main/java/org/moonshot/server/domain/log/model/LogState.java
  src/main/java/org/moonshot/server/domain/task/model/Task.java
Labels: 영린🐣

#23 [Docs] #22 - README.md 수정
  README.md
Labels: 영린🐣

#25 [Setting] #19 - Swagger 세팅
  build.gradle
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 영린🐣, 민철👃🏼

#27 [Feat] #24 - OKR 생성, 삭제 API 구현
  src/main/java/org/moonshot/server/domain/keyResult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultDeleteRequestDto.java
  src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultInvalidPositionException.java
  src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultNumberExceededException.java
  src/main/java/org/moonshot/server/domain/keyResult/model/KRState.java
  src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyResult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/model/Log.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/OKRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/TaskCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/exception/ObjectiveNotFoundException.java
  src/main/java/org/moonshot/server/domain/objective/exception/ObjectiveNumberExceededException.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveRepository.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/task/model/Task.java
  src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java
  src/main/java/org/moonshot/server/domain/user/exception/UserNotFoundException.java
  src/main/java/org/moonshot/server/domain/user/exception/exception
  src/main/java/org/moonshot/server/domain/user/model/User.java
  src/main/java/org/moonshot/server/domain/user/repository/UserRepository.java
  src/main/java/org/moonshot/server/domain/user/repository/repo
  src/main/java/org/moonshot/server/global/common/model/Period.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 민철👃🏼

#29 [Feat] #28 - KeyResult PATCH API 개발
  src/main/java/org/moonshot/server/domain/keyResult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultModifyRequestDto.java
  src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultNotFoundException.java
  src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyResult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/TaskCreateRequestDto.java
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java
  src/main/java/org/moonshot/server/global/common/model/validator/ValidTargetNumber.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 민철👃🏼

#31 [Feat] #30 - Task POST API 개발
  src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultInvalidPositionException.java
  src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultNumberExceededException.java
  src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/task/dto/request/TaskCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/dto/request/TaskSingleCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/exception/TaskInvalidPositionException.java
  src/main/java/org/moonshot/server/domain/task/exception/TaskNumberExceededException.java
  src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 민철👃🏼

#33 [Fix] #30 - 코드 병합 에러 해결
  src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java
Labels: 민철👃🏼

#35 [Refactor] #34 - KeyResult 삭제 API 수정
  src/main/java/org/moonshot/server/domain/keyResult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyResult/service/KeyResultService.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 민철👃🏼

#36 [Feat] #26 - 소셜로그인 API 구현
  build.gradle
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultDeleteRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidPositionException.java
  src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultNotFoundException.java
  src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultNumberExceededException.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KRState.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
  src/main/java/org/moonshot/server/domain/user/dto/dto
  src/main/java/org/moonshot/server/domain/user/dto/request/SocialLoginRequest.java
  src/main/java/org/moonshot/server/domain/user/dto/response/SocialLoginResponse.java
  src/main/java/org/moonshot/server/domain/user/dto/response/google/GoogleInfoResponse.java
  src/main/java/org/moonshot/server/domain/user/dto/response/google/GoogleTokenResponse.java
  src/main/java/org/moonshot/server/domain/user/dto/response/kakao/KakaoAccount.java
  src/main/java/org/moonshot/server/domain/user/dto/response/kakao/KakaoTokenResponse.java
  src/main/java/org/moonshot/server/domain/user/dto/response/kakao/KakaoUserProfile.java
  src/main/java/org/moonshot/server/domain/user/dto/response/kakao/KakaoUserResponse.java
  src/main/java/org/moonshot/server/domain/user/model/SocialPlatform.java
  src/main/java/org/moonshot/server/domain/user/model/User.java
  src/main/java/org/moonshot/server/domain/user/repository/UserRepository.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/domain/user/service/service
  src/main/java/org/moonshot/server/global/auth/exception/ExpiredTokenException.java
  src/main/java/org/moonshot/server/global/auth/exception/InvalidAuthException.java
  src/main/java/org/moonshot/server/global/auth/exception/InvalidRefreshTokenException.java
  src/main/java/org/moonshot/server/global/auth/feign/google/GoogleApiClient.java
  src/main/java/org/moonshot/server/global/auth/feign/google/GoogleAuthApiClient.java
  src/main/java/org/moonshot/server/global/auth/feign/kakao/KakaoApiClient.java
  src/main/java/org/moonshot/server/global/auth/feign/kakao/KakaoAuthApiClient.java
  src/main/java/org/moonshot/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/moonshot/server/global/auth/jwt/JwtValidationType.java
  src/main/java/org/moonshot/server/global/auth/jwt/TokenResponse.java
  src/main/java/org/moonshot/server/global/auth/redis/RefreshToken.java
  src/main/java/org/moonshot/server/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/org/moonshot/server/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/moonshot/server/global/auth/security/UserAuthentication.java
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/FeignConfig.java
  src/main/java/org/moonshot/server/global/config/RedisConfig.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/constants/AWSConstants.java
  src/main/java/org/moonshot/server/global/constants/JWTConstants.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 영린🐣

#38 [Feat] #37 - 닉네임 설정, 프로필 수정 API 개발
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
  src/main/java/org/moonshot/server/domain/user/dto/request/UserInfoRequest.java
  src/main/java/org/moonshot/server/domain/user/dto/response/UserInfoResponse.java
  src/main/java/org/moonshot/server/domain/user/model/User.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 영린🐣

#41 [Add] #40 - 기존에 구현한 API 유저 서비스 붙이기
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveRepository.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/auth/exception/AccessDeniedException.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 민철👃🏼

#45 [Add] #42 - Task, KeyResult 순서 변경 API
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/model/Log.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyIndexRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/model/IndexService.java
  src/main/java/org/moonshot/server/domain/objective/model/IndexTarget.java
  src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java
  src/main/java/org/moonshot/server/domain/task/dto/request/TaskCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/dto/request/TaskSingleCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/exception/TaskNotFoundException.java
  src/main/java/org/moonshot/server/domain/task/model/Task.java
  src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 민철👃🏼

#49 [Feat] #44 - KR 상세 조회
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/log/dto/response/LogResponseDto.java
  src/main/java/org/moonshot/server/domain/log/exception/InvalidLogValueException.java
  src/main/java/org/moonshot/server/domain/log/model/Log.java
  src/main/java/org/moonshot/server/domain/log/model/LogState.java
  src/main/java/org/moonshot/server/domain/log/repository/LogRepository.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/global/common/model/validator/LimitValueValidator.java
  src/main/java/org/moonshot/server/global/common/model/validator/ValidLimitValue.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 영린🐣

#51 [Fix] #50 - TokenResponse 수정 및 만료시간 변경 / Log 생성 관련 Exception 추가
  src/main/java/org/moonshot/server/domain/log/exception/InvalidRecordException.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/global/auth/jwt/TokenResponse.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/constants/JWTConstants.java
Labels: 영린🐣

#53 [Feat] #52 - O연장 및 O완료 API 구현
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyObjectiveRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/exception/InvalidExpiredAtException.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/model/Period.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 영린🐣

#57 [Feat] #48 - OKR 전체 보기(대시보드) API
  build.gradle
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/dto/response/LogResponseDto.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveRepository.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/task/dto/response/TaskResponseDto.java
  src/main/java/org/moonshot/server/domain/task/model/Task.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/resources/application.yml
Labels: 민철👃🏼

#66 [Feat] #56 - 마이페이지 조회 API 구현 및 프로필 수정 Validation 추가
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
  src/main/java/org/moonshot/server/domain/user/dto/request/UserInfoRequest.java
  src/main/java/org/moonshot/server/domain/user/dto/response/UserInfoResponse.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/constants/RegexConstants.java
Labels: 영린🐣

#65 [Chore] #54 -목표 달성 페이지를 위한 KR조회 Response 추가
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/log/dto/response/AchieveResponseDto.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
Labels: 영린🐣

#67 [Refactor] #64 - 클라이언트 날짜 타입 맞춰 데이터 처리
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/dto/response/LogResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyObjectiveRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/OKRCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/model/Period.java
Labels: 민철👃🏼

#70 [Hotfix] #69 : PR Merge import 문 빠진 문제 해결
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
Labels: 민철👃🏼

#71 [Refactor] #68 - 메인 대시보드 Objective 조회 프로그레스바 수치 및 만료 여부 추가
  src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
Labels: 민철👃🏼

#73 [Docs] #72 - 2차 과제 README.md 추가
  README.md
Labels: 영린🐣

#74 [Feat] #60 - KRDetailResponseDto, AchieveResponseDto 수정
  README.md
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/dto/response/AchieveResponseDto.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
Labels: 영린🐣

#77 [Fix] #76 - OKR 트리 POST, GET API JSON 클라이언트 요청으로 변경
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/TreeResponseDto.java
  src/main/java/org/moonshot/server/domain/task/dto/request/TaskCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/task/dto/response/TaskResponseDto.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
Labels: 민철👃🏼

#78 [Fix] KR, Log 관련 Validation 및 Exception 수정
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
  src/main/java/org/moonshot/server/domain/log/dto/request/LogCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/log/exception/InvalidRecordException.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
  src/main/java/org/moonshot/server/global/common/model/validator/LimitValueValidator.java
  src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java
  src/main/java/org/moonshot/server/global/common/model/validator/ValidLimitValue.java
  src/main/java/org/moonshot/server/global/common/model/validator/ValidTargetNumber.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
Labels: 영린🐣

#82 [Feat] #61 - 히스토리 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/ObjectiveHistoryRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryKeyResultDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryTaskDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveGroupByYearDto.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepository.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/QuerydslConfig.java
Labels: 민철👃🏼

#84 [Refactor] #83 - ObjectiveRepository 인터페이스 구조 변경
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveRepository.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
Labels: 민철👃🏼

#88 [Refactor] #85 - 코드 피드백 반영
  src/main/java/org/moonshot/server/domain/badge/model/Badge.java
  src/main/java/org/moonshot/server/domain/heart/model/Heart.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/model/Log.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/task/model/Task.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/domain/user/model/User.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/domain/userBadge/model/UserBadge.java
Labels: 민철👃🏼

#86 [Fix] #81 - 인증/인가 Exception Handling
  src/main/java/org/moonshot/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/moonshot/server/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/moonshot/server/global/auth/security/JwtExceptionFilter.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 영린🐣

#92 [Fix] #91 - permitAll 대상 API token validation 회피 로직 추가
  src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java
  src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#90 [Fix] #89 - ResponseEntity로 변경
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
Labels: 영린🐣

#94 [Fix] #93 - WhiteList 로그인 API 엔드포인트 추가 및 Token Authentication 회피 로직 변경
  src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#96 [Fix] #95 - 엑세스토큰 시간 1분으로 변경
  src/main/java/org/moonshot/server/global/constants/JWTConstants.java
Labels: 영린🐣

#97 [Feat] #87 - Swagger 적용
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
  src/main/java/org/moonshot/server/domain/user/controller/UserApi.java
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/common/response/ApiResponse.java
  src/main/java/org/moonshot/server/global/common/response/MoonshotResponse.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#102 [Feat] #99 - Objective, KeyResult Swagger 적용
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultApi.java
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#103 [Feat] #98 - Log, Task Swagger 적용 및 User Swagger 수정
  src/main/java/org/moonshot/server/domain/log/controller/LogApi.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskApi.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/user/controller/UserApi.java
Labels: 영린🐣

#105 [Refactor] #104 - KeyResult Description 요구사항 변경으로 엔티티 수정 및 로직 변경
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
Labels: 민철👃🏼

#108 [Fix] #106 - 예외 처리 추가 및 리드미 수정
  README.md
  src/main/java/org/moonshot/server/domain/objective/exception/DateInputRequiredException.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/moonshot/server/global/auth/security/JwtExceptionFilter.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
Labels: 영린🐣

#109 [Refactor] #107 - 히스토리 API 동적 쿼리 레포지토리 역할 줄이고 Service Layer에서 비즈니스 로직 처리로 변경
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultApi.java
  src/main/java/org/moonshot/server/domain/log/controller/LogApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepository.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskApi.java
  src/main/java/org/moonshot/server/domain/user/controller/UserApi.java
Labels: 민철👃🏼

#111 [Refactor] #110 - Index 수정 API Objective 추가 및 추가 예외 처리
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidIndexException.java
  src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyIndexRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java
  src/main/java/org/moonshot/server/domain/objective/exception/ObjectiveInvalidIndexException.java
  src/main/java/org/moonshot/server/domain/objective/model/IndexTarget.java
  src/main/java/org/moonshot/server/domain/objective/model/Objective.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java
  src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/task/exception/TaskInvalidIndexException.java
  src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
Labels: 민철👃🏼

#114 [Fix] #113 - OKR 데이터 존재하지 않을 때 Objective 조회 시 예외 처리
  src/main/java/org/moonshot/server/domain/objective/exception/UserObjectiveEmptyException.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
Labels: 민철👃🏼

#115 [Fix] #112 - KR 목표값, Log 진척상황 값 Max Validation 변경
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
  src/main/java/org/moonshot/server/domain/log/dto/request/LogCreateRequestDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
Labels: 영린🐣

#118 [Fix] #117 - Swagger generated Server https 설정
  src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
Labels: 민철👃🏼

#121 [Fix] #119 - Security Filter Swagger URI ignoring
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#122 [Hotfix] #119 - Security Filter Swagger URI ignoring Bean 등록
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 민철👃🏼

#124 [Refactor] #123 - History 조회 리팩토링
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveGroupByYearDto.java
  src/main/java/org/moonshot/server/domain/objective/model/Category.java
  src/main/java/org/moonshot/server/domain/objective/model/Criteria.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepository.java
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/objective/service/converter/CategoryConverter.java
  src/main/java/org/moonshot/server/domain/objective/service/converter/CriteriaConverter.java
Labels: 민철👃🏼

#126 [Fix] #125 - CORS 서버 URL 추가
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
Labels: 민철👃🏼

#128 [Fix] #127 - Moonshot Exception Discord 알림 제외, Security Config 재설정
  src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
Labels: 민철👃🏼

#132 [Fix] #129 - 히스토리 조회 NPE 해결 및 OKR 데이터 생성 API KeyResult 기간 관련 예외처리
  src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidPeriodException.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/response/ErrorType.java
Labels: 민철👃🏼

#133 [Feat] #116 - 회원가입 시 Discord 알림 추가
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
Labels: 영린🐣

#140 [Fix] #139 - KeyResult 및 Task 인덱스가 정상 위치에 있는지 예외 처리 및 메소드 분리 작업 진행
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
Labels: 민철👃🏼

#143 [Docs] #142 - README.md 수정
  README.md
Labels: 영린🐣

#146 [Fix] #144 - Objective 삭제 API 반환 데이터 204에서 200 DashboardDto 반환
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/exception/UserObjectiveEmptyException.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/global/common/response/SuccessType.java
  src/main/java/org/moonshot/server/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 민철👃🏼

#148 [Fix] #147 - Objective 삭제 API Swagger 설정 변경
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
Labels: 민철👃🏼

#149 [Fix] #145 - KR 상태 변경만 가능하도록 수정
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/dto/request/LogCreateRequestDto.java
Labels: 영린🐣

#151 [Fix] #150 - History KR title Response 수정
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryKeyResultDto.java
Labels: 영린🐣

#153 [Fix] #152 - OKR 리스트 조회 시 닉네임 Response 추가
  src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
Labels: 영린🐣

#156 [Fix] #155 - DTO String 내용 수정
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
  src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
Labels: 민철👃🏼

#158 [Fix] #157 - 도메인 변경으로 인한 코드 수정
  src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
Labels: 영린🐣

#160 [Fix] History 날짜 String 포맷팅 변경
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java
Labels: 민철👃🏼

#163 [Fix] #162 - OKR 데이터 생성 API KR List에서 NPE 발생 처리
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
Labels: 민철👃🏼

#161 [Feat] #154 - 회원가입 디스코드 알림 추가
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/common/util/ApiCallUtil.java
  src/main/java/org/moonshot/server/global/constants/DiscordConstants.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordWebHook.java
  src/main/resources/application-dev.yml
Labels: 영린🐣

#165 [Fix] #164 - History 조회 API years List로 변경
  src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryResponseDto.java
  src/main/java/org/moonshot/server/domain/objective/dto/response/YearDto.java
Labels: 민철👃🏼

#167 [Refactor] #166 - 회원가입 디스코드 알림 리팩토링
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/constants/DiscordConstants.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
Labels: 영린🐣

#169 [Fix] #168 - 회원가입 알림 안오는 이슈 해결
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
Labels: 영린🐣

#170 [Del] #168 - 디스코드 알림 이미지 썸네일 삭제
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
Labels: 영린🐣

#174 [Fix] 히스토리 조회 달성률 조건 정렬 버그 픽스
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
Labels: 민철👃🏼

#176 [Fix] #175 - KR 기간 수정 가능하도록 코드 수정
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
Labels: 영린🐣

#178 [Fix] #177 - 더미 데이터 주입을 위한 CI.yml 수정
  .github/workflows/CI.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 민철👃🏼

#180 [Fix] #179 - 더미 데이터 주입을 위한 CD.yml 수정
  .github/workflows/CD.yml
Labels: 민철👃🏼

#182 [Fix] #181 - KR 수정시 달성률 오류 수정
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
Labels: 영린🐣

#184 [Fix] #183 - 대시보드 데이터 조회 API 버그 수정
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
Labels: 민철👃🏼

#186 [Fix] #185 - 히스토리 기본 정렬 최신순으로 안되는 버그 수정
  src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
Labels: 민철👃🏼

#188 [Fix] #187 - 카카오 회원가입 시 디스코드 알림 안오는 이슈 해결
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/constants/JWTConstants.java
Labels: 영린🐣

#190 [Fix] #189 - 엑세스 토큰 만료기간 2주로 변경
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
  src/main/java/org/moonshot/server/global/constants/JWTConstants.java
  src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
Labels: 영린🐣

#192 [Refactor] #191 - 불변 변수 final 키워드 붙이기
  src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
  src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
  src/main/java/org/moonshot/server/domain/log/controller/LogController.java
  src/main/java/org/moonshot/server/domain/log/service/LogService.java
  src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
  src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
  src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java
  src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
  src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
  src/main/java/org/moonshot/server/domain/task/service/TaskService.java
  src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
  src/main/java/org/moonshot/server/domain/user/controller/UserController.java
  src/main/java/org/moonshot/server/domain/user/service/UserService.java
Labels: 민철👃🏼

#196 [Fix] #195 - Dockerfile build 파일 위치 수정
  Dockerfile
Labels: 민철👃🏼

#198 [Docs] #197 - README.md 디렉토리 수정 및 SpringBoot Version 수정
  README.md
Labels: 민철👃🏼
